### ISSUE TITLE
Commands for Assigning and Managing Roles

### ISSUE THREAD

**Issue by awhigham9** [ufosc/ALBot-2.0#2]
# `/giveRole` Command

**Create a slash command that allows server members to assign themselves a role. For example, `/giveRole <role_name>` will give the sender the role with name `<role_name>`.** This command should allow users to give themselves only roles from an approved list of roles, the "permit list".

# `/openRole` and `/closeRole` Commands

**Create an admin-only slash command used to add roles to the "permit list": `/openRole <role_name>`.** When an admin runs this command, it will "permit" the role with name `<role_name>` and make it possible for non-admin users to give themselves this role using `/giveRole`. 

**Create an admin-only slash command used to remove roles from the "permit list":  `/closeRole <role_name>`.** When an admin runs this command, it will "block" the role with name `<role_name>` and make it impossible for non-admin users to give themselves this role using `/giveRole`. 

It would be ideal if the "permit list" was persistent across bot startups. This could be implemented with a small SQLite database, or even a basic read/write JSON file. (Bonus Feature: It would be great if a configuration file could provided via the command line when starting the bot to pre-populate the "permit list". Otherwise, the "permit list" will start empty).

# `/roles` Command

Create a command to see what roles are on the "permit list", `/roles`. This should return a message indicating which roles are self-assignable with `/giveRole`.

# User Story Example

For example, suppose the server has roles `[role1, role2, moderator]` where `moderator` is a server-specific privileged role. The admin will not want non-admin users be able to self-assign the `moderator` role. Then, the admin will run `/openRole role1` and `openRole role2` to permit users to self-assign these roles using `/giveRole role1` or `/giveRole role2`.

Feel free to suggest modifications to these three role commands here, or open other issues for extensions to these commands elsewhere!

**Comment by logandgsmith** [comment]
@MesaJonathan it doesn't look like it. Are you interested in trying it out?

**Comment by MesaJonathan** [comment]
Ya, I'm taking a look at it but to be honest I have a lot of work so it might take me a while. If anyone else sees this and wants to tackle it now go ahead.

**Comment by skbt27i** [comment]
I can start working on this, though anyone else is welcome to join me

**Comment by skbt27i** [comment]
refer to [branch](https://github.com/ufosc/ALBot-2.0/tree/roles)
