### ISSUE TITLE
Commands for Finding Information about Projects

### ISSUE THREAD

**Issue by awhigham9** [ufosc/ALBot-2.0#4]
Create commands for finding information about active club projects, such as associated roles, GitHub repositories, related tutorials, etc.

Feel free to recommend ideas for project-related commands in this thread!

**Comment by awhigham9** [comment]
Hey @devp4, are you still working on this issue?

**Comment by devp4** [comment]
Hey, sorry I have been busy lately but I can work on it today

**Comment by skbt27i** [comment]
I can begin working on this as well

**Comment by devp4** [comment]
sounds good! do you have a discord so we can collaborate on it?

**Comment by skbt27i** [comment]
its Santosh Tirumala in the officer channel

**Comment by awhigham9** [comment]
@devp4 Are you ready to open the PR with what you have on the "projects" branch? Or are you planning on doing more?

**Comment by devp4** [comment]
I need to add 1 more error handling. I will have the PR open tonight

**Comment by devp4** [comment]
opened!
