### ISSUE TITLE
Add Centralized Code for Logging

### ISSUE THREAD

**Issue by awhigham9** [ufosc/ALBot-2.0#6]
Add utilities to the code for logging information into a log file while the bot is deployed on the server.

The logs should offer several different levels of message severity. For example levels might include, in increasing severity:
+ Debug
+ Info
+ Warning
+ Error
+ Critical

It would be best to accomplish this using a high-quality logging library offered through `npm`. A custom implementation will work if there isn't a suitable library available. 

Once the logging utility is added, the other files in the code base should begin to incorporate it for event-driven logging.

**Comment by logandgsmith** [comment]
Would suggest looking into Winston (https://github.com/winstonjs/winston). I've used it for projects in the past. Alternatively, someone trying to learn more about JS/TS might want to try writing their own library simple library first. It's a good exercise to to test out some concepts.
